---
- name: Manage Windows VMs
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Read VM settings from CSV
      community.general.read_csv:
        path: files/vm_settings.csv
      register: csv_data

    - name: Set VM settings fact
      set_fact:
        vm_settings: "{{ csv_data.list }}"

    - name: Print VM settings
      ansible.builtin.debug:
        msg: "{{ vm_settings }}"

- name: Apply settings to Windows VMs
  hosts: windows
  gather_facts: no
  roles:
    - role: update_ip
      vars:
        vm_settings: "{{ hostvars['localhost'].vm_settings }}"
