---
- name: Gather network interfaces
  ansible.windows.win_shell: |
    $interface = Get-WmiObject -Class Win32_NetworkAdapterConfiguration | Where-Object { $_.IPEnabled -eq $true } | Select-Object -First 1 -ExpandProperty Description
    $interface
  register: network_interface_name

- name: Set network interface fact
  set_fact:
    network_interface: "{{ network_interface_name.stdout.strip() }}"
