####WORKING########
- name: Manage Windows VMs
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Read VM settings from CSV
      community.general.read_csv:
        path: files/vm_settings.csv
      register: csv_data

    - name: Set VM settings fact
      set_fact:
        vm_settings: "{{ csv_data.list }}"

    - name: Print VM settings
      ansible.builtin.debug:
        msg: "{{ vm_settings }}"

- name: Apply settings to Windows VMs
  hosts: windows
  vars_files:
    - vault.yml
    - vars.yml
  gather_facts: no
  tasks:
    # - name: Apply IP address settings #Uncomment if this will be used
    #   ansible.builtin.include_role:
    #     name: win_update_ip
    #   vars:
    #     vm_settings: "{{ hostvars['localhost'].vm_settings }}"

    - name: Manage domain and workgroup
      ansible.builtin.include_role:
        name: win_domain_mgmt
      vars:
        vm_settings: "{{ hostvars['localhost'].vm_settings }}"

    # - name: Debug variables
    #   debug:
    #     msg:
    #       - "ansible_user: {{ ansible_user }}"
    #       - "ansible_password: {{ ansible_password }}"
    #       - "dns_domain_name: {{ dns_domain_name }}"
    #       - "domain_ou_path: {{ domain_ou_path }}"
    #       - "domain_admin_user: {{ domain_admin_user }}"
    #       - "domain_admin_password: {{ domain_admin_password }}"







# ###TEST
# - name: Manage Windows VMs
#   hosts: localhost
#   gather_facts: no
#   tasks:
#     - name: Read VM settings from CSV
#       community.general.read_csv:
#         path: files/vm_settings.csv
#       register: csv_data

#     - name: Set VM settings fact
#       set_fact:
#         vm_settings: "{{ csv_data.list }}"

#     - name: Print VM settings
#       ansible.builtin.debug:
#         msg: "{{ vm_settings }}"

# - name: Apply settings to Windows VMs
#   hosts: windows
#   gather_facts: no
#   tasks:
#     # - name: Apply IP address settings
#     #   ansible.builtin.include_role:
#     #     name: win_update_ip
#     #   vars:
#     #     vm_settings: "{{ hostvars['localhost'].vm_settings }}"

#     - name: Manage domain and workgroup
#       ansible.builtin.include_role:
#         name: win_domain_mgmt
#       vars:
#         vm_settings: "{{ hostvars['localhost'].vm_settings }}"
