name: Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Set up Python
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: 3.x

    # - name: Install Ansible
    #   run: pip install ansible

    - name: Run Ansible Playbook
      env:
        VAULT_PASSWORD: ${{ secrets.VAULT_PASS }}
      run: |
        cd RKT_DevOps/ansible_windows
        ansible-playbook -i inventory.ini win_updates.yml --vault-password-file <(echo $VAULT_PASS)
